const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();
const nodemailer = require('nodemailer');

let transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: "mypython.botmail@gmail.com", // generated by Mailtrap
      pass: "CCLYRDOCTOR2002" // generated by Mailtrap
    }
  });
exports.emailSender = functions.https.onRequest((req, res) => {

    const mailOptions = {
    from: 'mypython.botmail@gmail.com', //Adding sender's email
    to: "davidhuertasortiz@gmail.com", //Getting recipient's email by query string
    subject: "Email de " + req.query.name, //Email subject
    html: req.query.email + '<br/>' + req.query.content //Email content in HTML
};
res.set("Access-Control-Allow-Origin", "https://davidhuertas.dev")
res.set("Access-Control-Allow-Headers", "Content-Type");
return transporter.sendMail(mailOptions, (err, info) => {
    if(err){
        return res.send(err.toString());
    }
    return res.send('EMAIL_SENT');
});

});